// Package ooo implements out-of-office auto-replies for the headless daemon.
//
// Safety properties (see AGENTS.md):
//   - replies go only to screened-in senders, and only to the sender address
//     (Reply-To preferred, From fallback) — never to Cc recipients
//   - one reply per sender per OOO period, persisted in a cache file so
//     daemon restarts never cause duplicate replies
//   - auto-generated mail (mailing lists, bounces, other auto-responders)
//     never receives a reply, and our replies carry Auto-Submitted /
//     X-Auto-Response-Suppress headers so other systems don't reply back
//     (mail-loop protection, RFC 3834)
package ooo

import (
	"bufio"
	"fmt"
	"net/mail"
	"net/textproto"
	"os"
	"strings"
	"time"

	"github.com/sspaeti/neomd/internal/config"
	"github.com/sspaeti/neomd/internal/imap"
	"github.com/sspaeti/neomd/internal/smtp"
)

// DefaultSubject is used when [ooo].subject is empty.
const DefaultSubject = "Out of Office"

// Footer is appended to every OOO reply body — transparency that the reply
// was automated (rendered as a link in the HTML part, like any composed
// markdown).
const Footer = "*automatically sent from [neomd](https://neomd.ssp.sh)*"

// location resolves the timezone from/until are interpreted in: the
// configured IANA name, or the daemon machine's local time when unset.
func location(cfg config.OOOConfig) (*time.Location, error) {
	if cfg.Timezone == "" {
		return time.Local, nil
	}
	return time.LoadLocation(cfg.Timezone)
}

// parseWhen accepts "YYYY-MM-DD" or "YYYY-MM-DD HH:MM" in the given location.
// hasTime reports whether a time-of-day was given.
func parseWhen(s string, loc *time.Location) (t time.Time, hasTime bool, err error) {
	if t, err = time.ParseInLocation("2006-01-02 15:04", s, loc); err == nil {
		return t, true, nil
	}
	t, err = time.ParseInLocation("2006-01-02", s, loc)
	return t, false, err
}

// Active reports whether OOO auto-replies should run at the given time.
// An unparseable from/until value or unknown timezone fails safe: inactive.
func Active(cfg config.OOOConfig, now time.Time) bool {
	if !cfg.Enabled {
		return false
	}
	loc, err := location(cfg)
	if err != nil {
		return false
	}
	if cfg.From != "" {
		from, _, err := parseWhen(cfg.From, loc)
		if err != nil || now.Before(from) {
			return false
		}
	}
	if cfg.Until == "" {
		return true
	}
	until, hasTime, err := parseWhen(cfg.Until, loc)
	if err != nil {
		return false
	}
	if hasTime {
		return now.Before(until)
	}
	// Date-only: active through the end of the until day (inclusive).
	return now.Before(until.AddDate(0, 0, 1))
}

// Period identifies the configured OOO window ("from..until", "open" for
// unset ends) — the cache key: changing either date starts a fresh period
// where every sender may receive one new reply.
func Period(cfg config.OOOConfig) string {
	from, until := cfg.From, cfg.Until
	if from == "" {
		from = "open"
	}
	if until == "" {
		until = "open"
	}
	return from + ".." + until
}

// StartFor returns when the OOO period begins: the configured from moment
// (that day's midnight, or the exact time when given) — mail arriving from
// then onward gets a reply — otherwise now (activation time — pre-existing
// inbox mail is never answered).
func StartFor(cfg config.OOOConfig, now time.Time) time.Time {
	if cfg.From != "" {
		if loc, err := location(cfg); err == nil {
			if from, _, err := parseWhen(cfg.From, loc); err == nil {
				return from
			}
		}
	}
	return now
}

// IsAutoGenerated inspects a raw message's headers and reports whether it was
// produced by an automated system (auto-responder, mailing list, bounce).
// Such mail must never receive an OOO reply — this is the RFC 3834 loop guard.
func IsAutoGenerated(raw []byte) bool {
	idx := strings.Index(string(raw), "\r\n\r\n")
	headerBlock := raw
	if idx >= 0 {
		headerBlock = raw[:idx+4]
	}
	tp := textproto.NewReader(bufio.NewReader(strings.NewReader(string(headerBlock))))
	hdr, err := tp.ReadMIMEHeader()
	if err != nil && len(hdr) == 0 {
		// Unparseable headers: fail safe, treat as auto-generated (no reply).
		return true
	}
	if v := strings.ToLower(strings.TrimSpace(hdr.Get("Auto-Submitted"))); v != "" && v != "no" {
		return true
	}
	switch strings.ToLower(strings.TrimSpace(hdr.Get("Precedence"))) {
	case "bulk", "junk", "list", "auto_reply":
		return true
	}
	if hdr.Get("List-Id") != "" || hdr.Get("List-Unsubscribe") != "" {
		return true
	}
	if hdr.Get("X-Auto-Response-Suppress") != "" || hdr.Get("X-Autoreply") != "" || hdr.Get("X-Autorespond") != "" {
		return true
	}
	return false
}

// ReplyAddress returns the bare, lowercased address an OOO reply should go to:
// Reply-To when present, otherwise From. Empty string if neither parses.
// Cc recipients are intentionally never considered.
func ReplyAddress(e imap.Email) string {
	for _, candidate := range []string{e.ReplyTo, e.From} {
		if candidate == "" {
			continue
		}
		if addr, err := mail.ParseAddress(candidate); err == nil {
			return strings.ToLower(addr.Address)
		}
		// Fallback for bare or slightly malformed addresses.
		if addrs := imap.SplitAddrs(candidate); len(addrs) > 0 {
			return strings.ToLower(addrs[0])
		}
	}
	return ""
}

// Body resolves the reply body markdown: body_file wins over body, and the
// account's plain-text signature is appended exactly like the composer does
// (editor.Prelude separator), so OOO replies look like hand-written neomd mail.
func Body(cfg config.OOOConfig, sig config.SignatureConfig) (string, error) {
	body := cfg.Body
	if cfg.BodyFile != "" {
		data, err := os.ReadFile(cfg.BodyFile)
		if err != nil {
			return "", fmt.Errorf("read ooo body_file: %w", err)
		}
		body = strings.TrimRight(string(data), "\n")
	}
	if sig.Text != "" {
		body += "\n\n--  \n" + sig.Text + "\n"
	}
	// The footer marks the reply as automated — but if the signature already
	// carries the sent-from-neomd link (the default signature does), keep
	// just that: never two neomd lines in one reply.
	if !strings.Contains(sig.Text, "neomd.ssp.sh") && !strings.Contains(sig.HTML, "neomd.ssp.sh") {
		body = strings.TrimRight(body, "\n") + "\n\n" + Footer + "\n"
	}
	return body, nil
}

// BuildReply builds the raw MIME auto-reply. It reuses the exact same message
// builder as the compose flow (markdown → multipart/alternative with goldmark
// HTML, threading headers), then prepends the RFC 3834 auto-reply headers.
func BuildReply(from, to, subject, markdownBody, htmlSignature string, orig imap.Email) ([]byte, error) {
	if subject == "" {
		subject = DefaultSubject
	}
	raw, err := smtp.BuildMessageWithThreading(from, to, "", subject, markdownBody, nil, htmlSignature, orig.MessageID, orig.References)
	if err != nil {
		return nil, err
	}
	// Prepending extra headers before the existing header block is valid
	// RFC 5322; header order is not significant.
	autoHdrs := []byte("Auto-Submitted: auto-replied\r\nX-Auto-Response-Suppress: All\r\n")
	return append(autoHdrs, raw...), nil
}

// ShouldConsider applies the cheap (header-only) reply filters to one inbox
// email and returns the reply address if it passes: sender must be
// screened-in, not one of our own addresses, not already replied to, and the
// mail must have arrived after the OOO period started. The expensive
// IsAutoGenerated check on the raw message runs separately, after this.
func ShouldConsider(e imap.Email, started time.Time, ownAddrs map[string]bool, screenedIn, hasReplied func(string) bool) (string, bool) {
	addr := ReplyAddress(e)
	if addr == "" {
		return "", false
	}
	if ownAddrs[addr] {
		return "", false
	}
	if !e.Date.After(started) {
		return "", false
	}
	if !screenedIn(addr) {
		return "", false
	}
	if hasReplied(addr) {
		return "", false
	}
	return addr, true
}

// Cache tracks which senders already received a reply in the current OOO
// period, plus when the period started (so pre-OOO inbox mail is never
// answered). Persisted as a small line-based file, appended on each reply.
type Cache struct {
	path    string
	period  string
	started time.Time
	replied map[string]bool
}

// LoadCache reads the cache file at path. period identifies the current OOO
// period (the until date, or "open"); if the file was written for a different
// period the cache starts fresh and the file is rewritten on first update.
func LoadCache(path, period string) (*Cache, error) {
	c := &Cache{path: path, period: period, replied: make(map[string]bool)}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return c, nil
		}
		return nil, err
	}
	filePeriod := ""
	var started time.Time
	replied := make(map[string]bool)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		switch {
		case line == "" || strings.HasPrefix(line, "#"):
		case strings.HasPrefix(line, "period "):
			filePeriod = strings.TrimSpace(strings.TrimPrefix(line, "period "))
		case strings.HasPrefix(line, "started "):
			if t, err := time.Parse(time.RFC3339, strings.TrimSpace(strings.TrimPrefix(line, "started "))); err == nil {
				started = t
			}
		default:
			replied[strings.ToLower(line)] = true
		}
	}
	if filePeriod != period {
		// New OOO period: previous replies don't count anymore.
		return c, nil
	}
	c.started = started
	c.replied = replied
	return c, nil
}

// Started returns when the current OOO period began (zero if not yet set).
func (c *Cache) Started() time.Time { return c.started }

// SetStarted records the OOO period start and rewrites the cache file header.
func (c *Cache) SetStarted(t time.Time) error {
	c.started = t
	return c.rewrite()
}

// HasReplied reports whether addr already received a reply this period.
func (c *Cache) HasReplied(addr string) bool {
	return c.replied[strings.ToLower(addr)]
}

// MarkReplied records addr as replied and persists immediately. Call it
// BEFORE sending — a crash mid-send must never lead to a duplicate reply.
func (c *Cache) MarkReplied(addr string) error {
	addr = strings.ToLower(addr)
	if c.replied[addr] {
		return nil
	}
	c.replied[addr] = true
	return c.rewrite()
}

// rewrite persists the full cache state atomically enough for our needs
// (single daemon writer, tiny file).
func (c *Cache) rewrite() error {
	var b strings.Builder
	b.WriteString("# neomd out-of-office reply cache — one line per sender already replied to\n")
	b.WriteString("period " + c.period + "\n")
	if !c.started.IsZero() {
		b.WriteString("started " + c.started.Format(time.RFC3339) + "\n")
	}
	for addr := range c.replied {
		b.WriteString(addr + "\n")
	}
	return os.WriteFile(c.path, []byte(b.String()), 0o600)
}
