package ooo

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/sspaeti/neomd/internal/config"
	"github.com/sspaeti/neomd/internal/imap"
)

// --- Active window ---

func TestActive_DisabledIsInactive(t *testing.T) {
	cfg := config.OOOConfig{Enabled: false, Body: "away"}
	if Active(cfg, time.Now()) {
		t.Fatal("disabled OOO must be inactive")
	}
}

func TestActive_EnabledNoUntilIsActive(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away"}
	if !Active(cfg, time.Now()) {
		t.Fatal("enabled OOO without until must be active")
	}
}

func TestActive_UntilIsInclusiveEndOfDay(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", Until: "2026-09-07"}
	during := time.Date(2026, 9, 7, 23, 0, 0, 0, time.Local)
	after := time.Date(2026, 9, 8, 0, 30, 0, 0, time.Local)
	if !Active(cfg, during) {
		t.Fatal("OOO must be active through the until day (inclusive)")
	}
	if Active(cfg, after) {
		t.Fatal("OOO must auto-disable after the until day")
	}
}

func TestActive_BadUntilIsInactive(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", Until: "not-a-date"}
	if Active(cfg, time.Now()) {
		t.Fatal("unparseable until must fail safe (inactive)")
	}
}

// --- Auto-generated mail detection (loop protection) ---

func rawWith(headers string) []byte {
	return []byte("From: a@example.com\r\n" + headers + "Subject: hi\r\n\r\nbody\r\n")
}

func TestIsAutoGenerated(t *testing.T) {
	cases := []struct {
		name    string
		raw     []byte
		autoGen bool
	}{
		{"plain mail", rawWith(""), false},
		{"auto-submitted auto-replied", rawWith("Auto-Submitted: auto-replied\r\n"), true},
		{"auto-submitted auto-generated", rawWith("Auto-Submitted: auto-generated\r\n"), true},
		{"auto-submitted no", rawWith("Auto-Submitted: no\r\n"), false},
		{"precedence bulk", rawWith("Precedence: bulk\r\n"), true},
		{"precedence junk", rawWith("Precedence: junk\r\n"), true},
		{"precedence list", rawWith("Precedence: list\r\n"), true},
		{"list-id header", rawWith("List-Id: <dev.lists.example.com>\r\n"), true},
		{"x-auto-response-suppress", rawWith("X-Auto-Response-Suppress: All\r\n"), true},
		{"x-autoreply", rawWith("X-Autoreply: yes\r\n"), true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := IsAutoGenerated(c.raw); got != c.autoGen {
				t.Fatalf("IsAutoGenerated = %v, want %v", got, c.autoGen)
			}
		})
	}
}

// --- Reply address resolution ---

func TestReplyAddress_PrefersReplyTo(t *testing.T) {
	e := imap.Email{From: "Alice <alice@example.com>", ReplyTo: "Alice Work <work@example.com>"}
	if got := ReplyAddress(e); got != "work@example.com" {
		t.Fatalf("got %q, want work@example.com", got)
	}
}

func TestReplyAddress_FallsBackToFrom(t *testing.T) {
	e := imap.Email{From: "Alice <Alice@Example.com>"}
	if got := ReplyAddress(e); got != "alice@example.com" {
		t.Fatalf("got %q, want lowercased alice@example.com", got)
	}
}

func TestReplyAddress_EmptyFrom(t *testing.T) {
	if got := ReplyAddress(imap.Email{}); got != "" {
		t.Fatalf("got %q, want empty", got)
	}
}

// --- Body assembly (same look as composed mail: text signature appended like editor.Prelude) ---

func TestBody_AppendsTextSignatureLikeComposer(t *testing.T) {
	cfg := config.OOOConfig{Body: "I'm away until Sep 7."}
	sig := config.SignatureConfig{Text: "*sent from neomd*"}
	got, err := Body(cfg, sig)
	if err != nil {
		t.Fatal(err)
	}
	want := "I'm away until Sep 7.\n\n--  \n*sent from neomd*\n"
	if got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestBody_NoSignature(t *testing.T) {
	got, err := Body(config.OOOConfig{Body: "away"}, config.SignatureConfig{})
	if err != nil {
		t.Fatal(err)
	}
	if got != "away" {
		t.Fatalf("got %q, want %q", got, "away")
	}
}

func TestBody_BodyFileOverrides(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ooo.md")
	if err := os.WriteFile(path, []byte("file body\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := Body(config.OOOConfig{Body: "inline", BodyFile: path}, config.SignatureConfig{})
	if err != nil {
		t.Fatal(err)
	}
	if got != "file body" {
		t.Fatalf("got %q, want file body (trimmed)", got)
	}
}

// --- Reply message construction ---

func TestBuildReply_LooksLikeNormalNeomdMailPlusAutoHeaders(t *testing.T) {
	orig := imap.Email{
		From:       "Alice <alice@example.com>",
		Subject:    "project question",
		MessageID:  "<orig-id@example.com>",
		References: "<root-id@example.com>",
	}
	raw, err := BuildReply("Me <me@ssp.sh>", "alice@example.com", "Out of Office", "I'm **away**.", "", orig)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"Auto-Submitted: auto-replied",
		"X-Auto-Response-Suppress: All",
		"In-Reply-To: <orig-id@example.com>",
		"References: <root-id@example.com> <orig-id@example.com>",
		"To: alice@example.com",
		"Subject: Out of Office",
		"multipart/alternative", // same MIME shape as a composed neomd email
		"text/html",
	} {
		if !bytes.Contains(raw, []byte(want)) {
			t.Fatalf("built reply missing %q\n---\n%s", want, raw)
		}
	}
	if bytes.Contains(raw, []byte("Cc:")) {
		t.Fatal("OOO reply must never carry a Cc header")
	}
}

// --- Reply-once cache ---

func TestCache_MarkAndHasRepliedPersists(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ooo_replied")
	c, err := LoadCache(path, "2026-09-07")
	if err != nil {
		t.Fatal(err)
	}
	if c.HasReplied("alice@example.com") {
		t.Fatal("fresh cache must be empty")
	}
	if err := c.MarkReplied("alice@example.com"); err != nil {
		t.Fatal(err)
	}
	if !c.HasReplied("alice@example.com") {
		t.Fatal("MarkReplied must be visible immediately")
	}
	// reload — must persist
	c2, err := LoadCache(path, "2026-09-07")
	if err != nil {
		t.Fatal(err)
	}
	if !c2.HasReplied("alice@example.com") {
		t.Fatal("MarkReplied must persist across reloads")
	}
}

func TestCache_PeriodChangeResets(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ooo_replied")
	c, err := LoadCache(path, "2026-09-07")
	if err != nil {
		t.Fatal(err)
	}
	if err := c.MarkReplied("alice@example.com"); err != nil {
		t.Fatal(err)
	}
	// new vacation period → everyone may get a fresh reply
	c2, err := LoadCache(path, "2026-12-24")
	if err != nil {
		t.Fatal(err)
	}
	if c2.HasReplied("alice@example.com") {
		t.Fatal("changing the OOO period must reset the replied cache")
	}
}

func TestCache_StartedPersistsAcrossReloads(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ooo_replied")
	c, err := LoadCache(path, "open")
	if err != nil {
		t.Fatal(err)
	}
	if !c.Started().IsZero() {
		t.Fatal("fresh cache must have zero start")
	}
	start := time.Date(2026, 8, 31, 8, 0, 0, 0, time.UTC)
	if err := c.SetStarted(start); err != nil {
		t.Fatal(err)
	}
	c2, err := LoadCache(path, "open")
	if err != nil {
		t.Fatal(err)
	}
	if !c2.Started().Equal(start) {
		t.Fatalf("started = %v, want %v", c2.Started(), start)
	}
}

// --- Candidate selection (daemon decision logic) ---

func TestShouldConsider(t *testing.T) {
	started := time.Date(2026, 8, 31, 8, 0, 0, 0, time.UTC)
	own := map[string]bool{"me@ssp.sh": true}
	screenedIn := func(a string) bool { return a == "alice@example.com" }
	replied := func(a string) bool { return a == "bob@example.com" }

	mk := func(from string, when time.Time) imap.Email {
		return imap.Email{From: from, Date: when}
	}
	after := started.Add(time.Hour)

	cases := []struct {
		name     string
		e        imap.Email
		wantAddr string
		wantOK   bool
	}{
		{"screened-in sender after start", mk("Alice <alice@example.com>", after), "alice@example.com", true},
		{"not screened in", mk("stranger@example.com", after), "", false},
		{"own address never gets a reply", mk("me@ssp.sh", after), "", false},
		{"arrived before OOO started", mk("alice@example.com", started.Add(-time.Hour)), "", false},
		{"unparseable sender", mk("", after), "", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			addr, ok := ShouldConsider(c.e, started, own, screenedIn, replied)
			if addr != c.wantAddr || ok != c.wantOK {
				t.Fatalf("got (%q, %v), want (%q, %v)", addr, ok, c.wantAddr, c.wantOK)
			}
		})
	}

	// already-replied is checked via the replied func
	addr, ok := ShouldConsider(mk("bob@example.com", after), started, own, func(string) bool { return true }, replied)
	if ok {
		t.Fatalf("already-replied sender must be skipped, got (%q, %v)", addr, ok)
	}
}

// --- Subject: the configured subject verbatim, original subject never appended ---

func TestBuildReply_SubjectIsConfiguredValueVerbatim(t *testing.T) {
	orig := imap.Email{From: "a@example.com", Subject: "project question", MessageID: "<x@e>"}
	raw, err := BuildReply("Me <me@ssp.sh>", "a@example.com", "Out of Office", "away", "", orig)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(raw, []byte("Subject: Out of Office\r\n")) {
		t.Fatalf("subject must be the configured value verbatim, nothing appended\n---\n%s", raw)
	}
}

func TestBuildReply_EmptySubjectUsesDefault(t *testing.T) {
	orig := imap.Email{From: "a@example.com", Subject: "project question", MessageID: "<x@e>"}
	raw, err := BuildReply("Me <me@ssp.sh>", "a@example.com", "", "away", "", orig)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(raw, []byte("Subject: Out of Office\r\n")) {
		t.Fatalf("empty subject must yield the bare default subject\n---\n%s", raw)
	}
}

// --- from date: enable OOO starting a future day ---

func TestActive_FromDateGates(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", From: "2026-09-01", Until: "2026-09-04"}
	before := time.Date(2026, 8, 31, 23, 0, 0, 0, time.Local)
	onFrom := time.Date(2026, 9, 1, 0, 30, 0, 0, time.Local)
	if Active(cfg, before) {
		t.Fatal("OOO must be inactive before the from day")
	}
	if !Active(cfg, onFrom) {
		t.Fatal("OOO must be active from 00:00 of the from day")
	}
}

func TestActive_BadFromIsInactive(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", From: "tomorrow"}
	if Active(cfg, time.Now()) {
		t.Fatal("unparseable from must fail safe (inactive)")
	}
}

func TestPeriod_CoversFromAndUntil(t *testing.T) {
	if got := Period(config.OOOConfig{From: "2026-09-01", Until: "2026-09-04"}); got != "2026-09-01..2026-09-04" {
		t.Fatalf("got %q", got)
	}
	if got := Period(config.OOOConfig{}); got != "open..open" {
		t.Fatalf("got %q", got)
	}
}

func TestStartFor_UsesFromDayElseNow(t *testing.T) {
	now := time.Date(2026, 9, 2, 10, 0, 0, 0, time.Local)
	got := StartFor(config.OOOConfig{From: "2026-09-01"}, now)
	want := time.Date(2026, 9, 1, 0, 0, 0, 0, time.Local)
	if !got.Equal(want) {
		t.Fatalf("got %v, want from-day midnight %v", got, want)
	}
	if got := StartFor(config.OOOConfig{}, now); !got.Equal(now) {
		t.Fatalf("without from, start must be now; got %v", got)
	}
}

// --- optional time in from/until ("YYYY-MM-DD HH:MM") ---

func TestActive_FromWithTime(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", From: "2026-08-31 16:00"}
	before := time.Date(2026, 8, 31, 15, 59, 0, 0, time.Local)
	after := time.Date(2026, 8, 31, 16, 1, 0, 0, time.Local)
	if Active(cfg, before) {
		t.Fatal("must be inactive before the from time")
	}
	if !Active(cfg, after) {
		t.Fatal("must be active after the from time")
	}
}

func TestActive_UntilWithTimeIsExact(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", Until: "2026-09-04 08:00"}
	before := time.Date(2026, 9, 4, 7, 59, 0, 0, time.Local)
	after := time.Date(2026, 9, 4, 8, 1, 0, 0, time.Local)
	if !Active(cfg, before) {
		t.Fatal("must be active before the until time")
	}
	if Active(cfg, after) {
		t.Fatal("must be inactive after the exact until time")
	}
}

func TestStartFor_FromWithTime(t *testing.T) {
	now := time.Date(2026, 9, 1, 10, 0, 0, 0, time.Local)
	got := StartFor(config.OOOConfig{From: "2026-08-31 16:00"}, now)
	want := time.Date(2026, 8, 31, 16, 0, 0, 0, time.Local)
	if !got.Equal(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}

// --- explicit timezone: dates/times mean YOUR timezone, wherever the daemon runs ---

func TestActive_TimezoneInterpretsFromInThatZone(t *testing.T) {
	// 11:00 Zurich (CEST, UTC+2) == 09:00 UTC
	cfg := config.OOOConfig{Enabled: true, Body: "away", From: "2026-08-31 11:00", Timezone: "Europe/Zurich"}
	before := time.Date(2026, 8, 31, 8, 59, 0, 0, time.UTC)
	after := time.Date(2026, 8, 31, 9, 1, 0, 0, time.UTC)
	if Active(cfg, before) {
		t.Fatal("08:59 UTC is before 11:00 Zurich — must be inactive")
	}
	if !Active(cfg, after) {
		t.Fatal("09:01 UTC is after 11:00 Zurich — must be active")
	}
}

func TestActive_BadTimezoneIsInactive(t *testing.T) {
	cfg := config.OOOConfig{Enabled: true, Body: "away", From: "2026-08-31", Timezone: "Mars/Olympus"}
	if Active(cfg, time.Now()) {
		t.Fatal("unknown timezone must fail safe (inactive)")
	}
}

func TestStartFor_UsesTimezone(t *testing.T) {
	zurich, err := time.LoadLocation("Europe/Zurich")
	if err != nil {
		t.Skip("no tzdata")
	}
	now := time.Date(2026, 9, 1, 10, 0, 0, 0, time.UTC)
	got := StartFor(config.OOOConfig{From: "2026-08-31 11:00", Timezone: "Europe/Zurich"}, now)
	want := time.Date(2026, 8, 31, 11, 0, 0, 0, zurich)
	if !got.Equal(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}
