package ui

// HelpSection is one group of keybindings shown in the ? help overlay
// and in the generated documentation.
type HelpSection struct {
	Title string
	Rows  [][2]string // {key, description}
}

// HelpSections is the single source of truth for the user-facing shortcut map.
// The map deliberately keeps the captain's lowercase actions while borrowing
// vim's movement, operators, counts, and command-line habits. Compatibility
// aliases are called out inline so the primary map remains easy to scan.
var HelpSections = []HelpSection{
	{"Actions", [][2]string{
		{"e", "mark done / archive (alias A)"},
		{"E", "mark not done / move back to Inbox"},
		{"h", "remind me (quick picks / natural language)"},
		{"u", "undo the last move or delete"},
		{"U / z", "toggle unread-only view"},
		{"n", "mark read / unread"},
		{"N", "jump to next unread"},
		{"i", "approve sender / screened-in"},
		{"o", "open the selected email"},
		{"O", "screen out in the inbox; expand all in a conversation"},
		{"p", "mark as PaperTrail"},
		{"b", "move to Work"},
		{"ctrl+e", "open the emoji reaction picker"},
		{"@", "show every email from the selected sender across folders"},
		{"! / $", "mark spam"},
		{"# / dd", "move to Trash"},
		{"F", "mark as Feed (uppercase: f is forward)"},
		{"S", "dry-run screen"},
		{"R", "reload the current folder"},
	}},
	{"Conversations", [][2]string{
		{"r", "reply"},
		{"ctrl+r", "reply all"},
		{"f", "forward"},
		{"t", "open the full conversation thread (alias T)"},
		{"O", "expand all messages in a conversation / open in browser elsewhere"},
		{"enter", "open the selected email"},
		{"q / esc", "back to the inbox"},
		{"n / p", "next / previous message in a thread"},
	}},
	{"Messages", [][2]string{
		{"s / c", "start a new email"},
		{";", "open the snippets picker"},
		{"o", "open the selected email (enter is the full-word alias)"},
		{"<space>o", "open links and attachments in the browser"},
		{"1-9", "open attachment 1-9"},
		{"<space>1-0", "open link 1-10"},
		{"<space>e", "open the raw email in the editor"},
		{"y", "open the copy menu (m Message-ID link; w web link)"},
	}},
	{"Folders", [][2]string{
		{"gi", "Inbox"},
		{"gs", "Starred (when configured; otherwise reports unavailable)"},
		{"gd", "Drafts"},
		{"gt", "Sent"},
		{"ge", "Done / Archive"},
		{"gh", "Reminders / Waiting"},
		{"g;", "Snippets"},
		{"g!", "Spam"},
		{"g#", "Trash"},
		{"ga", "All Mail / Everything"},
		{"gl", "open the label / folder picker"},
		{"l", "add or remove a label with the folder picker"},
		{"go", "Other / ScreenedOut"},
		{"gm", "Muted / Someday"},
		{"gf", "Feed (neomd)"},
		{"gp", "PaperTrail (neomd)"},
		{"gk", "ToScreen (neomd)"},
		{"gw", "Waiting alias (neomd)"},
		{"gc", "Scheduled (neomd)"},
		{"gb", "Work (neomd, if configured)"},
		{"v / M*", "move to a folder with the picker / quick destination"},
		{"y", "remove label / move back to Inbox"},
	}},
	{"Selection", [][2]string{
		{"x / m", "select or unselect the current email"},
		{"V", "visual-select mode; j/k extend the selection"},
		{"ctrl+a", "select all loaded emails"},
		{"esc", "clear visual selection"},
		{"ctrl+d / ctrl+u", "half-page down / up"},
	}},
	{"Navigation", [][2]string{
		{"j / k", "move down / up"},
		{"gg / G", "jump to top / bottom"},
		{"/", "filter the loaded email list"},
		{"n / N", "next unread/read action (context dependent)"},
		{"tab / shift+tab", "next / previous folder tab"},
		{"<space>1 … <space>9", "jump to a folder tab"},
		{"<space>/", "search all mail on the server"},
		{"?", "toggle this help overlay"},
	}},
	{"Compose", [][2]string{
		{"a", "attach in pre-send"},
		{"<space>a", "attach in compose / pre-send"},
		{"<space>l / l", "send later"},
		{"<space>h", "remind while composing"},
		{"<space>;", "insert a snippet"},
		{"<space>o", "open links / attachments"},
		{"ctrl+enter / enter", "send from pre-send"},
		{"d", "save a draft from pre-send"},
		{"e", "re-open the editor from pre-send"},
		{"ctrl+b", "toggle Cc/Bcc"},
		{"ctrl+f", "cycle From identities"},
		{"x / esc", "discard the unsent message (with confirmation)"},
	}},
	{"Command line", [][2]string{
		{":", "open the vim-style command line"},
		{":screen / :s", "dry-run screening"},
		{":screen-all / :sa", "screen all Inbox mail"},
		{":reload / :r", "reload the current folder"},
		{":search / :se", "search all mail"},
		{":everything / :ev", "show All Mail"},
		{":check / :ch", "show sender classification"},
		{":reset-toscreen / :rts", "move ToScreen mail back to Inbox"},
		{":delete-all / :da", "permanently delete the current folder"},
		{":empty-trash / :et", "empty Trash"},
		{":go-spam / :spam", "open Spam"},
		{":create-folders / :cf", "create configured folders"},
		{":debug / :dbg", "write a diagnostic report"},
		{":quit / :q", "quit neomd"},
	}},
}
